name: CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pytest -v
      - name: Alerta - Build com sucesso
        if: success()
        run: echo "ALERTA: Pipeline executada com sucesso - 5 testes passaram"
      - name: Alerta - Falha no build
        if: failure()
        run: echo "ALERTA CRITICO: Falha no build"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy realizado com sucesso"
      - name: Alerta - Deploy realizado
        if: success()
        run: echo "ALERTA: Deploy OK na main"
