name: CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pytest -v
      - run: docker build -t meu-app.
      - name: Alerta sucesso
        if: success()
        run: echo "ALERTA: Pipeline OK - 5 testes passaram"
      - name: Alerta falha
        if: failure()
        run: echo "ALERTA: Falha no pipeline"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy realizado!"
      - name: Alerta deploy
        if: success()
        run: echo "ALERTA: Deploy OK"
